FORMAT: 1A
HOST: https://wayfarer-api-001.herokuapp.com/

# Wayfarer API

WayFarer is a public bus transportation booking server.


# Group Authentication

## Sign Up [/auth/signup]

### Sign Up User [POST]

Sign up a new user.

+ first_name (string) - User's first name (required).
+ last_name (string) - User's last name (required).
+ email (string) - User's email (required, unique).
+ password (string) - User's password (required).

+ Request (application/json)

    + Body

        {
            "first_name": "John",
            "last_name": "Doe",
            "email": "foo@bar.co",
            "password": "_P@ssw0rd_",
        }


+ Response 201 (application/json)

    + Body

        {
            "status": "success",
            "data":
                {
                    "user_id": 1,
                    "token": "faniuq8rq29nq92nfqio2jfn2uf29fu2209fn20qojf2q9u2o",
                    "is_admin": false
                },
        }

## Sign In [/auth/signin]

### Sign In User [POST]

Sign in a new user.

+ email (string) - User's email (required, unique).
+ password (string) - User's password (required).

+ Request (application/json)

    + Body

        {
            "email": "foo@bar.co",
            "password": "_P@ssw0rd_",
        }


+ Response 201 (application/json)

    + Body

        {
            "status": "success",
            "data":
                {
                    "user_id": 1,
                    "token": "faniuq8rq29nq92nfqio2jfn2uf29fu2209fn20qojf2q9u2o",
                    "is_admin": false
                },
        }

# Group Authentication

## Trip [/trips]

### Create a trip [POST]

Create a trip

+ bus_id (id) - bus for the trip (required).
+ origin (string) - City the journey starts from (required).
+ destination (string) - City the journey ends (required).
+ trip_date (date) - The date the trip will begin (required).
+ fare (float) - Price of trip (required).

+ Request (application/json)

    + Body

        {
            "bus_id": 3
            "origin": "abuja"
            "destination": "lagos"
            "trip_date": "2019-12-21T00:00:00.000Z"
            "fare": "2000.00"
        }

+ Response 201 (application/json)

    + Body

        {
            "status": "success",
            "data":
                {
                    "id": 3
                    "bus_id": 3
                    "origin": "abuja"
                    "destination": "lagos"
                    "trip_date": "2019-12-21T00:00:00.000Z"
                    "fare": "2000.00"
                },
        }
